### ISSUE TITLE
Add exception when errors in logging variables

### ISSUE THREAD

**Issue by Dynnammo** [OpenSourcePolitics/metabase_automation#13]
Currently, when launching the script and having an error in credentials, the error is a bit difficult to understand

**What would be great**
When detecting an error in `fetch_token` raise a `CredentialException` to enlight the user about the fact that it's credentials are wrong

**Comment by Quentinchampenois** [comment]
Nice feedback, I work on it ASAP !

**Comment by Dynnammo** [comment]
Not useful
