### ISSUE TITLE
Rename repo more clearly

### ISSUE THREAD

**Issue by Dynnammo** [OpenSourcePolitics/metabase_automation#15]
Since `decidim_metabase` is too close from `decidim-module_metabase`, another repo of ours, we should rename it `dashboard_automation` (or maybe `metabase_automation`) since it's purpose is to automate the creation of models, and then the creation of questions and dashboards.

**Comment by Quentinchampenois** [comment]
To me it's better `metabase_automation` because it is more precise

**Comment by Dynnammo** [comment]
LGTM

**Comment by Quentinchampenois** [comment]
Done ✅
